version: "3"

services:
  ws:
    image: ws
    container_name: ws
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=development"
    depends_on:
      - "db"
  db:
    image: postgres:10.3
    container_name: db
    ports:
    - 5432:5432
    restart: always
    environment:
    - POSTGRES_PASSWORD=Sergey03
    - POSTGRES_USER=postgres
    - POSTGRES_DB=postgres
    - PGDATA=/var/lib/postgresql/data